### ISSUE TITLE
go get 报错

### ISSUE THREAD

**Issue by 15951836388** [KorokEngine/Korok#17]
![image](https://user-images.githubusercontent.com/14047483/37528464-ab19bd6e-296f-11e8-9293-96d97cbbfa4f.png)

对这个引擎很感兴趣，加油

**Comment by 15951836388** [comment]
希望可以在wiki里 多介绍 这个引擎的模块和架构

**Comment by ntop001** [comment]
这是我本地的一个工程还没有更新到 github. 暂留TODO.

**Comment by 15951836388** [comment]
啥时能跑起来啊？不知道用korok的ui来做go的桌面应用是否可行？

**Comment by ntop001** [comment]
@15951836388 现在应该可以了（没测试），做一些小工具是可以的，但是不适合做大型桌面应用。GUI系统用的是immediate-mode的设计，每帧都会刷新整个页面，对于大型卓明应用来说是比较耗电的。

**Comment by ntop001** [comment]
国内同学下载 `golang.org/x/` 中的库是需要翻墙的，这需要自行解决.
