### ISSUE TITLE
install korok error

### ISSUE THREAD

**Issue by castorhrio** [KorokEngine/Korok#19]
I user command go get  korok.io/korok install korok ,but installation error like this:cc1.exe: sorry, unimplemented: 64-bit mode not compiled . I install gcc 64-bit, re-install korok, it still error.
![image](https://user-images.githubusercontent.com/11894921/41671909-116215dc-74eb-11e8-8c95-295109167f97.png)

**Comment by ntop001** [comment]
Windows is not well tested, now. I'll leave this issue open until we have a working version.

**Comment by vanishs** [comment]
Windows is working now, but it's not perfect yet.
