### ISSUE TITLE
Question： Is this engine support shader glsl ?

### ISSUE THREAD

**Issue by fastfading** [KorokEngine/Korok#23]
1  Is this engine support shader glsl ?how ? anydemos ? is shader portable ?

2 how to transition from 1 scene to another ?  any scene concept like other engine

3 any resource encryption ?

**Comment by ntop001** [comment]
1. The interface is not hardcoded and designed to support customized glsl, but I didn't test it, too
2.  Scene is managed as a stack in korok, just pop/push
3. no
@fastfading
