### ISSUE TITLE
不支持编辑器控件

### ISSUE THREAD

**Issue by evilbinary** [KorokEngine/Korok#24]
你好，看了一下发现不支持编辑器控件

**Comment by ntop001** [comment]
对，现在还不支持。当前引擎开发是跟着我们的项目走的，现在还没这方面需求，所以也没有开发。不过支持应该是早晚的事了。

**Comment by evilbinary** [comment]
@ntop001 物理引擎有么？

**Comment by ntop001** [comment]
@evilbinary https://github.com/ByteArena/box2d  这款游戏 [Unstable Tower](https://play.google.com/store/apps/details?id=io.korok.unstabletower)  使用了.
