### ISSUE TITLE
windos 上编译 直接报错

### ISSUE THREAD

**Issue by 15951836388** [KorokEngine/Korok#25]
windows上，有没有测试过？看报错内容，是声音部分的代码

还有引擎什么时候完善，可以让大家玩起来？

**Comment by ntop001** [comment]
Window 平台目前有两部分还没有测试：音频和OpenGL
音频模块现在还在调研方案，现在 MAC/iOS 现在是 OpenAL，Android 是 OpenSL|ES，Windows 计划使用 OpenAL-Soft 需要做一些适配工作，OpenGL 计划支持到2.1版本。音频工作量要大一些，现在挺忙的没时间做这部分支持，计划大概会在年前做吧.

**Comment by ntop001** [comment]
@15951836388 现在 @vanishs 正在支持windows方面的工作。

**Comment by vanishs** [comment]
目前windows已经可以编译通过。音频暂时使用winmm
