### ISSUE TITLE
table里的组件 删除，有问题

### ISSUE THREAD

**Issue by 15951836388** [KorokEngine/Korok#29]
发现删除后的引用，都乱了

**Comment by ntop001** [comment]
对的，Table里面是通过复制内存的方式来管理组件的。所以有个隐性的要求，组件只能通过 `comp := Table.Get(Entity)` 来读取，而不能直接持有 Component 的引用，因为下次这个引用的值很有可能就变掉了.

**Comment by 15951836388** [comment]
用Table.Get(Entity)来获取，还是乱的。
