### ISSUE TITLE
mac系统go get安装时提示有个文件名是 double bot

### ISSUE THREAD

**Issue by oliverCJ** [KorokEngine/Korok#35]
![image](https://user-images.githubusercontent.com/3614672/56408827-cf181300-62a8-11e9-9b7e-0053c8d1cbd6.png)
大佬，我的系统是mac 
go get安装时提示文件名有两个点？

**Comment by vanishs** [comment]
手误，已经修复了

**Comment by oliverCJ** [comment]
谢谢
