### ISSUE TITLE
golang 1.12 build时gl报错重复定义

### ISSUE THREAD

**Issue by oliverCJ** [KorokEngine/Korok#36]
大佬，使用golang 1.12版本，go mod模式build报错
![image](https://user-images.githubusercontent.com/3614672/56480759-16431580-64ee-11e9-9137-019b2c84fe5c.png)

实在找不到办法,只有删掉hid/gl/gl_gl2.go才能正确编译

请问大佬有什么优雅的解决办法吗？

**Comment by vanishs** [comment]
已经修复。您再试试

**Comment by oliverCJ** [comment]
恩，可以了，多谢，学到了
