### ISSUE TITLE
dbg.Move不存在

### ISSUE THREAD

**Issue by MoonRaito** [KorokEngine/Korok#37]
你好，很高兴看到go的游戏引擎

第一时间尝试运行，
当然也遇到一些问题，
在demo中，dbg.Move 提示不存在，查看dbg文件中没有Move方法，
这个问题是我clone文件的版本问题吗？

另外，dbg.DrawStr("Hello World") 查看dbg文件中
func DrawStr(x,y float32, str string, args ...interface{})
并没有这个方法。

我是一个go 的新手，有不对的地方请多多包涵

**Comment by ntop001** [comment]
@MoonRaito 官网的示例有点过时了（移除了 `dbg.Move` 方法），你可以先按照 https://github.com/KorokEngine/beta-demo 来学习和使用。稍后我们会更新官网的示例。

**Comment by MoonRaito** [comment]
顺便问下 会支持 砖块地图吗？

**Comment by ntop001** [comment]
@MoonRaito 在引擎中不会加入砖块地图支持，如果以后支持的话会以一个新的工程存在，尽量维持引擎的精简。
