### ISSUE TITLE
导入字体的时候我看文档是两个参数，实际使用的时候是三个参数啊大佬

### ISSUE THREAD

**Issue by wuxin469280855** [KorokEngine/Korok#39]
就是导入ttf的时候，我是个初学者，不太懂。如果方便的话希望能帮助一下

**Comment by ntop001** [comment]
@wuxin469280855 文档没有更新，可以参考一下字体渲染的DEMO： https://github.com/KorokEngine/demo/blob/master/text/main.go

```
asset.Font.LoadTrueType("font2", "OCRAEXT.TTF", font.ASCII(24))
```
主要是多了第三个参数，这个参数是一个加载配置，用来决定加载的字体文件要渲染的字符和字符的大小。在之前的版本默认了一个大小，但是实际渲染的时候字体可能大可能小，但是加载TTF的时候使用的大小和正真渲染的时候不一致会导致渲染模糊或者浪费资源。

`font.ASCII(24)` 告诉引擎，加载的字符为所有的 ASCII 码，字符大小为 24px。

这个大小，通常应该和我们实际渲染字符时的大小保持一致。
