### ISSUE TITLE
应该用什么屏幕适配方案？

### ISSUE THREAD

**Issue by likun123687** [KorokEngine/Korok#40]
rt

**Comment by ntop001** [comment]
下面是从我们的线上游戏中取出的一段代码：
```
// set font
	fnt, _ := asset.Font.Get("f1")
	gui.SetFont(fnt)
	gui.SetVirtualResolution(320, 0)
```
这段代码告诉GUI系统，设置虚拟的屏幕尺寸宽度为：320， 高度按比例计算。这样我们在绘制 GUI 的时候就可以按标准宽度 320px 来适配屏幕了。

这里也可以设置：`gui.SetVirtualResolution(0, 480)`, 这样的话会按照标准高度 480 来绘制，宽度按比例计算。如果同时设置了宽度和高度，则会对屏幕内的元素进行拉伸适配。
