### ISSUE TITLE
install error on arch linux

### ISSUE THREAD

**Issue by pangoSE** [KorokEngine/Korok#41]
I'm on parabola (arch linux):
$ uname -a
Linux parabola 5.5.1-gnu-1 #1 SMP PREEMPT Mon, 03 Feb 2020 22:37:39 +0000 x86_64 GNU/Linux

OpenAl is installed:
$ LANG=en_US.UTF-8 pacman -Si openal
Repository      : extra
Name            : openal
Version         : 1.20.1-2

$ go get korok.io/korok
# korok.io/korok/audio/sine
../src/korok.io/korok/audio/sine/bk_al.go:398:21: could not determine kind of name for C.AL_INVALID_ENUM
../src/korok.io/korok/audio/sine/bk_al.go:397:21: could not determine kind of name for C.AL_INVALID_NAME
../src/korok.io/korok/audio/sine/bk_al.go:400:21: could not determine kind of name for C.AL_INVALID_OPERATION
../src/korok.io/korok/audio/sine/bk_al.go:399:21: could not determine kind of name for C.AL_INVALID_VALUE
../src/korok.io/korok/audio/sine/bk_al.go:396:21: could not determine kind of name for C.AL_NO_ERROR
../src/korok.io/korok/audio/sine/bk_al.go:401:21: could not determine kind of name for C.AL_OUT_OF_MEMORY
../src/korok.io/korok/audio/sine/bk_al.go:188:29: could not determine kind of name for C.ALenum
../src/korok.io/korok/audio/sine/bk_al.go:264:42: could not determine kind of name for C.ALfloat
../src/korok.io/korok/audio/sine/bk_al.go:188:70: could not determine kind of name for C.ALsizei
../src/korok.io/korok/audio/sine/bk_al.go:178:11: could not determine kind of name for C.ALuint
../src/korok.io/korok/audio/sine/bk_al.go:235:12: could not determine kind of name for C.SineBufferPlayer_play
../src/korok.io/korok/audio/sine/bk_al.go:264:2: could not determine kind of name for C.SineBufferPlayer_setVolume
../src/korok.io/korok/audio/sine/bk_al.go:367:3: could not determine kind of name for C.SineStreamPlayer_feed
../src/korok.io/korok/audio/sine/bk_al.go:288:12: could not determine kind of name for C.SineStreamPlayer_init
../src/korok.io/korok/audio/sine/bk_al.go:338:2: could not determine kind of name for C.SineStreamPlayer_setVolume
../src/korok.io/korok/audio/sine/bk_al.go:188:2: could not determine kind of name for C.alBufferData
../src/korok.io/korok/audio/sine/bk_al.go:187:2: could not determine kind of name for C.alGenBuffers
cgo: 
gcc errors for preamble:
../src/korok.io/korok/audio/sine/bk_al.go:20:2: error: unknown type name 'ALCdevice'
   20 |  ALCdevice *device;
      |  ^~~~~~~~~
../src/korok.io/korok/audio/sine/bk_al.go:21:2: error: unknown type name 'ALCcontext'
   21 |  ALCcontext *context;
      |  ^~~~~~~~~~
../src/korok.io/korok/audio/sine/bk_al.go:24:1: error: unknown type name 'ALenum'; did you mean 'enum'?
   24 | ALenum Sine_init(SineEngine *eng) {
      | ^~~~~~
      | enum
../src/korok.io/korok/audio/sine/bk_al.go:42:2: error: unknown type name 'ALuint'
   42 |  ALuint idSource;
      |  ^~~~~~
../src/korok.io/korok/audio/sine/bk_al.go:45:1: error: unknown type name 'ALenum'; did you mean 'enum'?
   45 | ALenum SineBufferPlayer_init(SineBufferPlayer *p) {
      | ^~~~~~
      | enum
../src/korok.io/korok/audio/sine/bk_al.go: In function 'SineBufferPlayer_init':
../src/korok.io/korok/audio/sine/bk_al.go:46:2: error: unknown type name 'ALuint'
   46 |  ALuint id;
      |  ^~~~~~
../src/korok.io/korok/audio/sine/bk_al.go: At top level:
../src/korok.io/korok/audio/sine/bk_al.go:52:1: error: unknown type name 'ALenum'; did you mean 'enum'?
   52 | ALenum SineBufferPlayer_play(SineBufferPlayer *p, ALuint idBuffer) {
      | ^~~~~~
      | enum
../src/korok.io/korok/audio/sine/bk_al.go:52:51: error: unknown type name 'ALuint'
   52 | ALenum SineBufferPlayer_play(SineBufferPlayer *p, ALuint idBuffer) {
      |                                                   ^~~~~~
../src/korok.io/korok/audio/sine/bk_al.go:60:1: error: unknown type name 'ALenum'; did you mean 'enum'?
   60 | ALenum SineBufferPlayer_pause(SineBufferPlayer *p) {
      | ^~~~~~
      | enum
../src/korok.io/korok/audio/sine/bk_al.go:65:1: error: unknown type name 'ALenum'; did you mean 'enum'?
   65 | ALenum SineBufferPlayer_stop(SineBufferPlayer *p) {
      | ^~~~~~
      | enum
../src/korok.io/korok/audio/sine/bk_al.go:71:1: error: unknown type name 'ALenum'; did you mean 'enum'?
   71 | ALenum SineBufferPlayer_state(SineBufferPlayer *p) {
      | ^~~~~~
      | enum
../src/korok.io/korok/audio/sine/bk_al.go: In function 'SineBufferPlayer_state':
../src/korok.io/korok/audio/sine/bk_al.go:72:3: error: unknown type name 'ALenum'; did you mean 'enum'?
   72 |   ALenum state;
      |   ^~~~~~
      |   enum
../src/korok.io/korok/audio/sine/bk_al.go:73:29: error: 'AL_SOURCE_STATE' undeclared (first use in this function)
   73 |   alGetSourcei(p->idSource, AL_SOURCE_STATE, &state);
      |                             ^~~~~~~~~~~~~~~
../src/korok.io/korok/audio/sine/bk_al.go:73:29: note: each undeclared identifier is reported only once for each function it appears in
../src/korok.io/korok/audio/sine/bk_al.go: At top level:
../src/korok.io/korok/audio/sine/bk_al.go:77:1: error: unknown type name 'ALfloat'; did you mean 'float'?
   77 | ALfloat SineBufferPlayer_getVolume(SineBufferPlayer *p) {
      | ^~~~~~~
      | float
../src/korok.io/korok/audio/sine/bk_al.go: In function 'SineBufferPlayer_getVolume':
../src/korok.io/korok/audio/sine/bk_al.go:78:2: error: unknown type name 'ALfloat'; did you mean 'float'?
   78 |  ALfloat v;
      |  ^~~~~~~
      |  float
../src/korok.io/korok/audio/sine/bk_al.go:79:28: error: 'AL_GAIN' undeclared (first use in this function)
   79 |  alGetSourcef(p->idSource, AL_GAIN, &v);
      |                            ^~~~~~~
../src/korok.io/korok/audio/sine/bk_al.go: At top level:
../src/korok.io/korok/audio/sine/bk_al.go:83:54: error: unknown type name 'ALfloat'; did you mean 'float'?
   83 | void SineBufferPlayer_setVolume(SineBufferPlayer *p, ALfloat v) {
      |                                                      ^~~~~~~
      |                                                      float
../src/korok.io/korok/audio/sine/bk_al.go:88:2: error: unknown type name 'ALuint'
   88 |  ALuint idSource;
      |  ^~~~~~
../src/korok.io/korok/audio/sine/bk_al.go:89:2: error: unknown type name 'ALuint'
   89 |  ALuint buffers[8]; //max buffer size
      |  ^~~~~~
../src/korok.io/korok/audio/sine/bk_al.go:90:2: error: unknown type name 'ALuint'
   90 |  ALuint numBuffers; //buffer in use
      |  ^~~~~~
../src/korok.io/korok/audio/sine/bk_al.go:91:2: error: unknown type name 'ALuint'
   91 |  ALuint freed;      //buffer active
      |  ^~~~~~
../src/korok.io/korok/audio/sine/bk_al.go:94:1: error: unknown type name 'ALenum'; did you mean 'enum'?
   94 | ALenum SineStreamPlayer_init(SineStreamPlayer *p, ALuint numBuffers) {
      | ^~~~~~
      | enum
../src/korok.io/korok/audio/sine/bk_al.go:94:51: error: unknown type name 'ALuint'
   94 | ALenum SineStreamPlayer_init(SineStreamPlayer *p, ALuint numBuffers) {
      |                                                   ^~~~~~
../src/korok.io/korok/audio/sine/bk_al.go:107:1: error: unknown type name 'ALenum'; did you mean 'enum'?
  107 | ALenum SineStreamPlayer_play(SineStreamPlayer *p) {
      | ^~~~~~
      | enum
../src/korok.io/korok/audio/sine/bk_al.go:113:1: error: unknown type name 'ALenum'; did you mean 'enum'?
  113 | ALenum SineStreamPlayer_stop(SineStreamPlayer *p) {
      | ^~~~~~
      | enum
../src/korok.io/korok/audio/sine/bk_al.go:119:1: error: unknown type name 'ALenum'; did you mean 'enum'?
  119 | ALenum SineStreamPlayer_pause(SineStreamPlayer *p) {
      | ^~~~~~
      | enum
../src/korok.io/korok/audio/sine/bk_al.go:124:1: error: unknown type name 'ALuint'
  124 | ALuint SineStreamPlayer_freeBuffer(SineStreamPlayer *p) {
      | ^~~~~~
../src/korok.io/korok/audio/sine/bk_al.go: In function 'SineStreamPlayer_freeBuffer':
../src/korok.io/korok/audio/sine/bk_al.go:125:2: error: unknown type name 'ALuint'
  125 |  ALuint source = p->idSource;
      |  ^~~~~~
../src/korok.io/korok/audio/sine/bk_al.go:126:2: error: unknown type name 'ALuint'
  126 |  ALuint freed  = p->freed;
      |  ^~~~~~
../src/korok.io/korok/audio/sine/bk_al.go:128:2: error: unknown type name 'ALint'; did you mean 'int'?
  128 |  ALint bp;
      |  ^~~~~
      |  int
../src/korok.io/korok/audio/sine/bk_al.go:129:28: error: 'AL_BUFFERS_PROCESSED' undeclared (first use in this function)
  129 |  alGetSourcei(p->idSource, AL_BUFFERS_PROCESSED, &bp);
      |                            ^~~~~~~~~~~~~~~~~~~~
../src/korok.io/korok/audio/sine/bk_al.go: At top level:
../src/korok.io/korok/audio/sine/bk_al.go:140:61: error: unknown type name 'ALsizei'
  140 | void SineStreamPlayer_feed(SineStreamPlayer *p, void *data, ALsizei size, ALenum format, ALsizei freq) {
      |                                                             ^~~~~~~
../src/korok.io/korok/audio/sine/bk_al.go:140:75: error: unknown type name 'ALenum'; did you mean 'enum'?
  140 | void SineStreamPlayer_feed(SineStreamPlayer *p, void *data, ALsizei size, ALenum format, ALsizei freq) {
      |                                                                           ^~~~~~
      |                                                                           enum
../src/korok.io/korok/audio/sine/bk_al.go:140:90: error: unknown type name 'ALsizei'
  140 | void SineStreamPlayer_feed(SineStreamPlayer *p, void *data, ALsizei size, ALenum format, ALsizei freq) {
      |                                                                                          ^~~~~~~
../src/korok.io/korok/audio/sine/bk_al.go:150:1: error: unknown type name 'ALenum'; did you mean 'enum'?
  150 | ALenum SineStreamPlayer_state(SineStreamPlayer *p) {
      | ^~~~~~
      | enum
../src/korok.io/korok/audio/sine/bk_al.go: In function 'SineStreamPlayer_state':
../src/korok.io/korok/audio/sine/bk_al.go:151:3: error: unknown type name 'ALenum'; did you mean 'enum'?
  151 |   ALenum state;
      |   ^~~~~~
      |   enum
../src/korok.io/korok/audio/sine/bk_al.go:152:29: error: 'AL_SOURCE_STATE' undeclared (first use in this function)
  152 |   alGetSourcei(p->idSource, AL_SOURCE_STATE, &state);
      |                             ^~~~~~~~~~~~~~~
../src/korok.io/korok/audio/sine/bk_al.go: At top level:
../src/korok.io/korok/audio/sine/bk_al.go:157:1: error: unknown type name 'ALfloat'; did you mean 'float'?
  157 | ALfloat SineStreamPlayer_getVolume(SineStreamPlayer *p) {
      | ^~~~~~~
      | float
../src/korok.io/korok/audio/sine/bk_al.go: In function 'SineStreamPlayer_getVolume':
../src/korok.io/korok/audio/sine/bk_al.go:158:2: error: unknown type name 'ALfloat'; did you mean 'float'?
  158 |  ALfloat v;
      |  ^~~~~~~
      |  float
../src/korok.io/korok/audio/sine/bk_al.go:159:28: error: 'AL_GAIN' undeclared (first use in this function)
  159 |  alGetSourcef(p->idSource, AL_GAIN, &v);
      |                            ^~~~~~~
../src/korok.io/korok/audio/sine/bk_al.go: At top level:
../src/korok.io/korok/audio/sine/bk_al.go:163:54: error: unknown type name 'ALfloat'; did you mean 'float'?
  163 | void SineStreamPlayer_setVolume(SineStreamPlayer *p, ALfloat v) {
      |                                                      ^~~~~~~
      |                                                      float

**Comment by ntop001** [comment]
@pangoSE Linux 版本没有适配
